# 设置伪路径
set_false_path -from [get_cells eth_mac_regs_if_u/new_eth_tx_dsc_created_r] -to [get_cells sync_for_new_eth_tx_dsc_created_u/dff_chain[0].dffs[0]]
set_false_path -from [get_cells eth_mac_regs_if_u/eth_rx_dsc_free_r] -to [get_cells sync_for_eth_rx_dsc_free_u/dff_chain[0].dffs[0]]
set_false_path -from [get_cells mm2s_cmd_done_extended] -to [get_cells sync_for_mm2s_cmd_done_u/dff_chain[0].dffs[0]]
set_false_path -from [get_cells s2mm_cmd_done_extended] -to [get_cells sync_for_s2mm_cmd_done_u/dff_chain[0].dffs[0]]

set_false_path -from [get_cells eth_mac_regs_if_u/eth_tx_buf_baseaddr_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/eth_tx_dsc_buf_len_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/eth_rx_buf_baseaddr_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/eth_rx_dsc_buf_len_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/broadcast_accept_r]
set_false_path -from [get_cells eth_mac_regs_if_u/unicast_filter_mac_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/multicast_filter_mac_0_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/multicast_filter_mac_1_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/multicast_filter_mac_2_r[*]]
set_false_path -from [get_cells eth_mac_regs_if_u/multicast_filter_mac_3_r[*]]

set_false_path -from [get_cells axis_eth_mac_u/eth_mac_tx_u/eth_frame_wptr_at_w[0]] -to [get_cells axis_eth_mac_u/eth_mac_tx_u/sync_for_eth_frame_wptr_u0/dff_chain[0].dffs[0]]
set_false_path -from [get_cells axis_eth_mac_u/eth_mac_tx_u/eth_frame_wptr_at_w[1]] -to [get_cells axis_eth_mac_u/eth_mac_tx_u/sync_for_eth_frame_wptr_u1/dff_chain[0].dffs[0]]
set_false_path -from [get_cells axis_eth_mac_u/eth_mac_tx_u/eth_frame_rptr_at_r[0]] -to [get_cells axis_eth_mac_u/eth_mac_tx_u/sync_for_eth_frame_rptr_u0/dff_chain[0].dffs[0]]
set_false_path -from [get_cells axis_eth_mac_u/eth_mac_tx_u/eth_frame_rptr_at_r[1]] -to [get_cells axis_eth_mac_u/eth_mac_tx_u/sync_for_eth_frame_rptr_u1/dff_chain[0].dffs[0]]

set_false_path -from [get_cells axis_eth_mac_u/eth_mac_rx_u/eth_frame_wptr_at_w[0]] -to [get_cells axis_eth_mac_u/eth_mac_rx_u/sync_for_eth_frame_wptr_u0/dff_chain[0].dffs[0]]
set_false_path -from [get_cells axis_eth_mac_u/eth_mac_rx_u/eth_frame_wptr_at_w[1]] -to [get_cells axis_eth_mac_u/eth_mac_rx_u/sync_for_eth_frame_wptr_u1/dff_chain[0].dffs[0]]
set_false_path -from [get_cells axis_eth_mac_u/eth_mac_rx_u/eth_frame_rptr_at_r[0]] -to [get_cells axis_eth_mac_u/eth_mac_rx_u/sync_for_eth_frame_rptr_u0/dff_chain[0].dffs[0]]
set_false_path -from [get_cells axis_eth_mac_u/eth_mac_rx_u/eth_frame_rptr_at_r[1]] -to [get_cells axis_eth_mac_u/eth_mac_rx_u/sync_for_eth_frame_rptr_u1/dff_chain[0].dffs[0]]
